---
# silence ansible warnings
ansible_python_interpreter: auto_silent
networks_cli_compatible: no

timezone: Europe/Berlin

users:
  - name: lenni
    keys_url: https://github.com/leonardehrenfried.keys
  - name: becky
    keys_url: https://github.com/Beck-Berry.keys

server_name: "cycling-norway"

snow_plow_service_image: "ghcr.io/buskerudbyen/snow-plow-service:latest"

# Podman
podman_prune_max_age: 72h
podman_prune_users:
      - snow-plow-service

# ssh hardening
network_ipv6_enable: true
ssh_allow_agent_forwarding: true
ssh_permit_tunnel: true
ssh_allow_tcp_forwarding: 'yes'
sftp_enabled: true
sftp_chroot: true