---
collections:
- name: ansible.posix
  version: 1.4.0
- name: community.general
  version: 6.1.0
- name: community.dns
  version: 2.4.2
- name: leonardehrenfried.baseline
  version: 0.1.40
- name: devsec.hardening
  version: 8.4.0

roles:
- src: geerlingguy.swap
  version: 1.0.1
- src: geerlingguy.firewall
  version: 2.5.0
