---
- name: Create user otp
  user:
    name: snow-plowing-service
    state: present
    createhome: yes
    shell: /bin/bash

- name: Install systemd files
  ansible.builtin.template:
    src: systemd/{{ item }}
    dest: /etc/systemd/system/
  with_items:
    - snow-plowing.service

- name: Start services and timers
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - snow-plowing.service

- name: Caddyfile
  ansible.builtin.template:
    src: templates/Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy